-- Pepers cloud schema: Supabase PostgreSQL + Auth + RLS
-- The Android app keeps SQLite as its offline source of truth.
create extension if not exists pgcrypto;

create table if not exists public.user_profiles (user_id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '', phone text not null default '', email text not null default '', shop_name text not null default '', avatar_path text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.shops (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, legacy_id bigint not null, record_key text not null, source_device_id text not null, name text not null, default_worker_legacy_id bigint, registration_mode text not null default 'NUMERIC' check (registration_mode in ('NUMERIC', 'INDIVIDUAL')), registration_number text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, record_key));
create table if not exists public.workers (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, legacy_id bigint not null, record_key text not null, source_device_id text not null, shop_legacy_id bigint not null, shop_record_key text not null, name text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, record_key));
create table if not exists public.months (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, legacy_id bigint not null, record_key text not null, source_device_id text not null, shop_legacy_id bigint not null, shop_record_key text not null, worker_legacy_id bigint, worker_record_key text, year integer not null, month_number integer not null check(month_number between 1 and 12), name text not null, worker_name text not null default '', start_date text not null default '', deduct_expense boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, record_key));
create table if not exists public.pieces (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, legacy_id bigint not null, record_key text not null, source_device_id text not null, shop_legacy_id bigint not null, shop_record_key text not null, name text not null, price integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, record_key));
create table if not exists public.days (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, legacy_id bigint not null, record_key text not null, source_device_id text not null, month_legacy_id bigint not null, month_record_key text not null, date_value text not null, day_name text not null default '', expense integer not null default 0, expense_note text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, record_key));
create table if not exists public.entries (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, legacy_id bigint not null, record_key text not null, source_device_id text not null, day_legacy_id bigint not null, day_record_key text not null, piece_legacy_id bigint not null, piece_record_key text not null, quantity integer not null default 0, unit_price integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, record_key));
create table if not exists public.individual_entries (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, legacy_id bigint not null, record_key text not null, source_device_id text not null, day_legacy_id bigint not null, day_record_key text not null, customer_name text not null default '', page_number text not null default '', customer_search text not null default '', customer_search_dotless text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, record_key));
create table if not exists public.individual_entry_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, legacy_id bigint not null, record_key text not null, source_device_id text not null, entry_legacy_id bigint not null, entry_record_key text not null, piece_legacy_id bigint not null, piece_record_key text not null, quantity integer not null default 0, unit_price integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, record_key));

create or replace function public.set_updated_at() returns trigger language plpgsql security invoker set search_path = public as $$ begin new.updated_at = now(); return new; end; $$;
do $$ declare t text; begin foreach t in array array['user_profiles','shops','workers','months','pieces','days','entries','individual_entries','individual_entry_items'] loop execute format('drop trigger if exists %I on public.%I', 'set_updated_at_'||t, t); execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()', 'set_updated_at_'||t, t); end loop; end $$;

do $$ declare t text; begin foreach t in array array['user_profiles','shops','workers','months','pieces','days','entries','individual_entries','individual_entry_items'] loop execute format('alter table public.%I enable row level security', t); execute format('drop policy if exists %I on public.%I', t||'_owner_all', t); execute format('create policy %I on public.%I for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid())', t||'_owner_all', t); end loop; end $$;